/**
 * ...
 * @author Georgi Dimov georgi.dimov@egt-bg.com
 */

var CommonSettings =
{
	"translations":
	{
		"en": 
		{
			"Line":"Line",
			"LINES":"LINES",
			"BET":"BET",
			"RED":"RED",
			"BLACK":"BLACK",
			"FREE SPIN":"FREE<br>SPIN",
			"OF":"OF",
			"YOU WIN":"YOU WIN",
			"NO CONNECTION":"NO CONNECTION",
			"INSUFFICIENT BALANCE":"INSUFFICIENT BALANCE",
			"PLEASE PLACE YOUR BET":"PLEASE PLACE YOUR BET",
			"GOOD LUCK!":"GOOD LUCK!",
			"TOTAL BET":"TOTAL BET",
			"WIN":"WIN",
			"CREDIT":"CREDIT",
			"BALANCE":"BALANCE",
			"GAMBLE AMOUNT":"GAMBLE AMOUNT",
			"GAMBLE TO WIN":"GAMBLE TO WIN",
			"GAMBLE ATTEMPTS LEFT":"GAMBLE ATTEMPTS LEFT",
			"HISTORY":"HISTORY",
			"CHOOSE CARD":"CHOOSE CARD",
			"PRESS COLLECT TO END THIS FEATURE":"PRESS COLLECT TO END THIS FEATURE",
			"totalBetLabel":"TB:",
			"totalWinLabel":"TW:"
		}, 
		"bg": 
		{ 
			"Line":"          ",
			"LINES":"          ",
			"BET":"          ",
			"RED":"              ",
			"BLACK":"          ",
			"FREE SPIN":"                <br>        ",
			"OF":"    ",
			"YOU WIN":"                           ",
			"NO CONNECTION":"                     ",
			"INSUFFICIENT BALANCE":"                                     ",
			"PLEASE PLACE YOUR BET":"        ,                                         ",
			"GOOD LUCK!":"            !",
			"TOTAL BET":"                 ",
			"WIN":"              ",
			"CREDIT":"            ",
			"BALANCE":"            ",
			"GAMBLE AMOUNT":"                                ",
			"GAMBLE TO WIN":"                                     ",
			"GAMBLE ATTEMPTS LEFT":"                           ",
			"HISTORY":"              ",
			"CHOOSE CARD":"                           ",
			"PRESS COLLECT TO END THIS FEATURE":"                                                                        ",
			"totalBetLabel":"    :",
			"totalWinLabel":"    :"
		},
		"ru": 
		{ 
			"Line":"          ",
			"LINES":"          ",
			"BET":"            ",
			"RED":"              ",
			"BLACK":"            ",
			"FREE SPIN":"                  <br>        ",
			"OF":"    ",
			"YOU WIN":"                     ",
			"NO CONNECTION":"                 ",
			"INSUFFICIENT BALANCE":"                                       ",
			"PLEASE PLACE YOUR BET":"                    ,                                     ",
			"GOOD LUCK!":"          !",
			"TOTAL BET":"                       ",
			"WIN":"              ",
			"CREDIT":"            ",
			"BALANCE":"            ",
			"GAMBLE AMOUNT":"                           ",
			"GAMBLE TO WIN":"                                   ",
			"GAMBLE ATTEMPTS LEFT":"                                   ",
			"HISTORY":"              ",
			"CHOOSE CARD":"                           ",
			"PRESS COLLECT TO END THIS FEATURE":"                                                                            "
		},
		"nl": 
		{
			"Line":"Lijn",
			"LINES":"LIJNEN",
			"BET":"INZETTEN",
			"RED":"ROOD",
			"BLACK":"ZWART",
			"FREE SPIN":"FREE<br>SPIN",
			"OF":"VAN",
			"YOU WIN":"U WINT",
			"NO CONNECTION":"GEEN VERBINDING",
			"INSUFFICIENT BALANCE":"SALDO ONVOLDOENDE",
			"PLEASE PLACE YOUR BET":"INZETTEN ALSTUBLIEFT",
			"GOOD LUCK!":"VEEL SUCCES!",
			"TOTAL BET":"TOTALE INZET",
			"WIN":"WINST",
			"CREDIT":"CREDIT",
			"BALANCE":"SALDO",
			"GAMBLE AMOUNT":"INZETBEDRAG",
			"GAMBLE TO WIN":"GOK OM TE WINNEN",
			"GAMBLE ATTEMPTS LEFT":"RESTERENDE GOKPOGINGEN",
			"HISTORY":"GESCHIEDENIS",
			"CHOOSE CARD":"KIES KAART",
			"PRESS COLLECT TO END THIS FEATURE":"DRUK OP INNEN OM DEZE FUNCTIE TE BEEINDIGEN"
		},
		"fr": 
		{
			"Line":"Ligne",
			"LINES":"LIGNES",
			"BET":"MISE",
			"RED":"ROUGE",
			"BLACK":"NOIR",
			"FREE SPIN":"PARTIE<br>GRATUITE",
			"OF":"DE",
			"YOU WIN":"VOUS GAGNEZ",
			"NO CONNECTION":"PAS DE CONNEXION",
			"INSUFFICIENT BALANCE":"SOLDE INSUFFISANT",
			"PLEASE PLACE YOUR BET":"METTEZ VOTRE PARI, S'IL VOUS PLA  T",
			"GOOD LUCK!":"BONNE CHANCE!",
			"TOTAL BET":"MISE TOTALE",
			"WIN":"GAIN",
			"CREDIT":"CR  DIT",
			"BALANCE":"SOLDE",
			"GAMBLE AMOUNT":"MONTANT    OSER",
			"GAMBLE TO WIN":"OSER POUR GAGNER",
			"GAMBLE ATTEMPTS LEFT":"TENTATIVES &quot;OSER&quot; RESTANTES",
			"HISTORY":"HISTORIQUE",
			"CHOOSE CARD":"CHOISISSEZ UNE CARTE",
			"PRESS COLLECT TO END THIS FEATURE":"APPUYEZ SUR ENCAISSER POUR FIN DE PARTIE"
		},
		"mk": 
		{
			"Line":"            ",
			"LINES":"          ",
			"BET":"          ",
			"RED":"            ",
			"BLACK":"        ",
			"FREE SPIN":"                  <br>                    ",
			"OF":"    ",
			"YOU WIN":"                               ",
			"NO CONNECTION":"                        ",
			"INSUFFICIENT BALANCE":"                               ",
			"PLEASE PLACE YOUR BET":"                                                                 ",
			"GOOD LUCK!":"               !",
			"TOTAL BET":"                       ",
			"WIN":"              ",
			"CREDIT":"            ",
			"BALANCE":"            ",
			"GAMBLE AMOUNT":"                        ",
			"GAMBLE TO WIN":"                              ",
			"GAMBLE ATTEMPTS LEFT":"                                                     ",
			"HISTORY":"                ",
			"CHOOSE CARD":"                           ",
			"PRESS COLLECT TO END THIS FEATURE":"                                               "
		},
		"es": 
		{
			"Line":"L  nea",
			"LINES":"L  NEAS",
			"BET":"APUESTA",
			"RED":"ROJO",
			"BLACK":"NEGRO",
			"FREE SPIN":"JUEGO<br>GRATIS",
			"OF":"DE",
			"YOU WIN":"USTED GANA",
			"NO CONNECTION":"SIN CONEXI  N",
			"INSUFFICIENT BALANCE":"SALDO INSUFICIENTE",
			"PLEASE PLACE YOUR BET":"POR FAVOR, HAGA SU APUESTA",
			"GOOD LUCK!":"  BUENA SUERTE!",
			"TOTAL BET":"APUESTA TOTAL",
			"WIN":"GANANCIA",
			"CREDIT":"CR  DITO",
			"BALANCE":"SALDO",
			"GAMBLE AMOUNT":"APOSTAR IMPORTE",
			"GAMBLE TO WIN":"APUESTE PARA GANAR",
			"GAMBLE ATTEMPTS LEFT":"INTENTOS DE APUESTA DISPONOBLES",
			"HISTORY":"HISTORIAL",
			"CHOOSE CARD":"ELIJA UNA CARTA",
			"PRESS COLLECT TO END THIS FEATURE":"PULSE RECOGER PARA FINALIZAR ESTA CARACTER  STICA",
			"totalBetLabel":"TA:",
			"totalWinLabel":"TG:"
		},
		"ro": 
		{
			"Line":"Linie",
			"LINES":"LINII",
			"BET":"PARIU",
			"RED":"RO  U",
			"BLACK":"NEGRU",
			"FREE SPIN":"ROTIRE<br>GRATUIT  ",
			"OF":"DIN",
			"YOU WIN":"A  I C    TIGAT",
			"NO CONNECTION":"F  R   CONEXIUNE",
			"INSUFFICIENT BALANCE":"FONDURI INSUFICIENTE",
			"PLEASE PLACE YOUR BET":"V   RUG  M PLASA  I PARIUL",
			"GOOD LUCK!":"MULT NOROC!",
			"TOTAL BET":"TOTAL PARIU",
			"WIN":"C    TIG",
			"CREDIT":"CREDIT",
			"BALANCE":"BALAN    ",
			"GAMBLE AMOUNT":"SUM   GAMBLE",
			"GAMBLE TO WIN":"GAMBLE PENTRU C    TIG",
			"GAMBLE ATTEMPTS LEFT":"  NCERC  RI GAMBLE R  MASE",
			"HISTORY":"ISTORIC",
			"CHOOSE CARD":"ALEGE  I CARTE",
			"PRESS COLLECT TO END THIS FEATURE":"AP  SA  I COLECTA PT. A FINALIZA FUNC  IA",
			"totalBetLabel":"TB:",
			"totalWinLabel":"TW:"
		}, 
	}
}
/*var CommonSettings = 
{
	translations:
	{
		en: 
		{
			Start:"Start", 
			"Stop All":"Stop All",
			Collect:"Collect",
			Gamble:"Gamble",
			Autoplay:"Autoplay",
			Stop Auto:"Stop Auto",
			Exit:"Exit",
			Paytable:"Paytable",
			Help:"Help",
			Line:"Line",
			RED:"RED",
			BLACK:"BLACK",
			FREE SPIN:"FREE SPIN",
			OF:"OF",
			YOU WIN:"YOU WIN",
			"NO CONNECTION":"NO CONNECTION",
			INSUFFICIENT BALANCE:"INSUFFICIENT BALANCE",
			PLEASE PLACE YOUR BET:"PLEASE PLACE YOUR BET",
			GOOD LUCK!:"GOOD LUCK!",
			BET:"BET",
			CREDIT:"CREDIT",
			BALANCE:"BALANCE",
			GAMBLE AMOUNT:"GAMBLE AMOUNT",
			GAMBLE TO WIN:"GAMBLE TO WIN",
			GAMBLE ATTEMPTS LEFT:"GAMBLE ATTEMPTS LEFT",
			HISTORY:"HISTORY",
			CHOOSE CARD:"CHOOSE CARD",
			PRESS COLLECT TO END THIS FEATURE:"PRESS COLLECT TO END THIS FEATURE"
		}, 
		bg: 
		{ 
			Start:"          ", 
			Stop All:"        ", 
			Collect:"                ",
			Gamble:"              ",
			Autoplay:"                 ",
			Stop Auto:"                 ",
			Exit:"          ",
			Paytable:"              ",
			Help:"          ",
			Line:"          ",
			RED:"              ",
			BLACK:"          ",
			FREE SPIN:"                         ",
			OF:"    ",
			YOU WIN:"                           ",
			NO CONNECTION:"                     ",
			INSUFFICIENT BALANCE:"                                     ",
			PLEASE PLACE YOUR BET:"        ,                                         ",
			GOOD LUCK!:"            !",
			BET:"          ",
			CREDIT:"            ",
			BALANCE:"            ",
			GAMBLE AMOUNT:"                                ",
			GAMBLE TO WIN:"                                     ",
			GAMBLE ATTEMPTS LEFT:"                           ",
			HISTORY:"              ",
			CHOOSE CARD:"                           ",
			PRESS COLLECT TO END THIS FEATURE:"                                                                        "
		},
		ru: 
		{ 
			Start:"          ", 
			Stop All:"               ", 
			Collect:"          ",
			Gamble:"              ",
			Autoplay:"                 ",
			Stop Auto:"                 ",
			Exit:"          ",
			Paytable:"              ",
			Help:"            ",
			Line:"          ",
			RED:"              ",
			BLACK:"            ",
			FREE SPIN:"                           ",
			OF:"    ",
			YOU WIN:"                     ",
			NO CONNECTION:"                 ",
			INSUFFICIENT BALANCE:"                                       ",
			PLEASE PLACE YOUR BET:"                    ,                                     ",
			GOOD LUCK!:"          !",
			BET:"            ",
			CREDIT:"            ",
			BALANCE:"            ",
			GAMBLE AMOUNT:"                           ",
			GAMBLE TO WIN:"                                   ",
			GAMBLE ATTEMPTS LEFT:"                                   ",
			HISTORY:"              ",
			CHOOSE CARD:"                           ",
			PRESS COLLECT TO END THIS FEATURE:"                                                                            "
		}
	}
}*/